### ISSUE TITLE
https://gall.fxdcinside.com/bser/6186851 과 같은 마이너 갤러리의 주소에서 정보를 받아오지 못하고 있습니다.

### ISSUE THREAD

**Issue by xxs14c** [KOZ39/fxdcinside.com#1]

**Comment by KOZ39** [comment]
본문 하단 `공유` 버튼의 URL은  `/m`이 포함되어 있으나, 갤러리 메뉴 `갤주소 복사` 버튼의 URL은 `/m`이 포함되지 않네요.
공유 : https://gall.dcinside.com/m/bser/6186851
복사 : https://gall.dcinside.com/bser/6186851

복사 URL은 301 리다이렉션이 발생하는데, head 태그에 script 코드만 있어 og 태그 파싱이 불가능합니다.
